# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# You should also look at https://hp-theme.gbif-staging.org/documentation-intro for options
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Redbioma # the title of your site should go here
email: your-email@example.com
description: >- # this means to ignore newlines (until baseurl:)
  Red de Ciencia de Datos para la Conservación de la Biodiversidad Mesoamericana
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://redbioma.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yourname # if you have an account you want to link to. Else comment this line out
github_username:  yourname # if you have an account you want to link to. Else comment this line out

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: redbioma/jekyll-hp-base-theme

# For use by the 'standardPrivacy' layout
privacy:
  name: Your organisation name
  domain: your-domain.org
  contactEmail: info@your-domain.org
  helpdeskEmail: helpdesk@your-domain.org

algae:
  rootLang: es
  # latestPostLimit: 2
  logo: /assets/images/logos/ico_Redbioma_menu.png  # Logo in navbar, will be displayed with 28px height
  logoAndTitle: false           # include the title next to the logo
  archive_permalink: /news/       # Permalink of page using archive.html layout, required when using post categories
  style:
    # square: false               # Should corners be square or rounded
    colors:
      primary: "#008B89"
      secondary: "#D2D9A3"
      accent: "#BF4633"
      dark: "#0C2722"
      highlight: "#8C1C25"
      links: "#AA1713" #rojo   - "#0375B1" celeste - "#fa5e97" anterior

    coloredHeadlineLinks: false   # If a headline is a link, then use the link color. Default is true. 
  navbar:                         # RELATED TO NAVIGATION BAR
    # brandBackground: yellow     # Define a custom background for the logo/title in the top navigation bar
    # color: "tomato"             # What color should the navbar be?
    # hasWhiteText: true          # Should the text color be white?
     floating: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .LICENSE
  - .netlify.toml
  - .README.md

permalink: pretty # will strip extensions like .html from urls

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page" # So by default any page will use the layout "page"
      lang: es # And have the default language english
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      permalink: "/post/:year/:slug/"   # Use /post/yyyy/{filename}/ as permalink for all posts
  - scope:
      path: "en/"
    values:
      lang: en
  - scope:
      path: "_posts/en"
    values:
      layout: "post"
      permalink: "/en/post/:year/:slug/"
      lang: en